"""Blueprint collection for Corposostenibile Suite"""

from . import (
    auth,
    communications,
    customers,
    department,
    feedback,
    feedback_global,
    nutrition,
    postit,
    projects,
    recruiting,
    respond_io,
    review,
    sales_form,
    team,
    ticket,
    welcome,
    client_checks,
    manual,
    tasks,
    search,

)

__all__ = [
    'auth',
    'communications',
    'customers',
    'department',
    'feedback',
    'feedback_global',
    'nutrition',
    'postit',
    'projects',
    'recruiting',
    'respond_io',
    'review',
    'sales_form',
    'team',
    'ticket',
    'welcome',
    'client_checks',
    'manual',
    'tasks',
    'search',
]