"""Blueprint collection for Corposostenibile Suite"""

from . import (
    auth,
    communications,
    customers,
    feedback,
    nutrition,
    postit,
    recruiting,
    respond_io,
    review,
    push_notifications,
    sales_form,
    team,
    team_tickets,
    ticket,
    welcome,
    client_checks,
    tasks,
    search,
    sop_chatbot,
    monitoring,

)

__all__ = [
    'auth',
    'communications',
    'customers',
    'feedback',
    'nutrition',
    'postit',
    'recruiting',
    'respond_io',
    'review',
    'push_notifications',
    'sales_form',
    'team',
    'team_tickets',
    'ticket',
    'welcome',
    'client_checks',
    'tasks',
    'search',
    'sop_chatbot',
    'monitoring',
]
