site_name: Corposostenibile Documentation
site_dir: static

theme:
  name: material
  language: it
  custom_dir: overrides

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3

nav:
  - Benvenuto: index.md
  - Gestione Pazienti:
    - Lista Pazienti: pazienti/lista.md
    - Scheda Dettaglio: pazienti/dettaglio.md
  - Gestione Professionisti:
    - Task: professionisti/task.md
    - Formazione: professionisti/formazione.md
