apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-backups-pv-c
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard-rwo
  volumeMode: Filesystem
  csi:
    driver: pd.csi.storage.gke.io
    fsType: ext4
    volumeHandle: projects/suite-clinica/zones/europe-west8-c/disks/db-backups-pvc-c-20260221-172822
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.gke.io/zone
              operator: In
              values:
                - europe-west8-c
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-backups-pvc-c
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard-rwo
  volumeMode: Filesystem
  volumeName: db-backups-pv-c
