apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  labels:
    app: suite-clinica
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 200Gi
