export const SVGICON = {
    Dashboard: <i className="ri-dashboard-line sidebar-ri-icon"></i>,
    Calendar: <i className="ri-calendar-2-line sidebar-ri-icon"></i>,
    Chat: <i className="ri-chat-3-line sidebar-ri-icon"></i>,
    Task: <i className="ri-task-line sidebar-ri-icon"></i>,
    Learning: <i className="ri-graduation-cap-line sidebar-ri-icon"></i>,
    Health: <i className="ri-heart-pulse-line sidebar-ri-icon"></i>,
    PeopleArrow: <i className="ri-user-settings-line sidebar-ri-icon"></i>,
    Check: <i className="ri-checkbox-circle-line sidebar-ri-icon"></i>,
    Profile: <i className="ri-user-line sidebar-ri-icon"></i>,
    Team: <i className="ri-team-line sidebar-ri-icon"></i>,
    Users: <i className="ri-group-line sidebar-ri-icon"></i>,
    Quality: <i className="ri-bar-chart-box-line sidebar-ri-icon"></i>,
    Trial: <i className="ri-user-follow-line sidebar-ri-icon"></i>,
    Ghost: <i className="ri-ghost-line sidebar-ri-icon"></i>,
    Clock: <i className="ri-alarm-warning-line sidebar-ri-icon"></i>,
    Refresh: <i className="ri-refresh-line sidebar-ri-icon"></i>,
}
