"""Sync with Main Task System

Revision ID: d62ad1702238
Revises: d6e5f4a3b2c1
Create Date: 2026-01-26 18:12:18.713377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd62ad1702238'
down_revision = 'd6e5f4a3b2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # TASKS Table Updates
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        # Aggiunta colonna category (Enum)
        # Nota: il tipo ENUM verrà creato automaticamente se non esiste
        batch_op.add_column(sa.Column('category', sa.Enum('onboarding', 'check', 'reminder', 'formazione', 'sollecito', 'generico', name='taskcategoryenum'), server_default='generico', nullable=False))
        
        # Aggiunta colonna payload (JSON)
        batch_op.add_column(sa.Column('payload', sa.JSON(), nullable=True))
        
        # Department ID nullable
        batch_op.alter_column('department_id',
               existing_type=sa.Integer(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.Integer(),
               nullable=False)
        batch_op.drop_column('payload')
        batch_op.drop_column('category')

    # Drop Enum type explicitly if needed, but usually left as artifact or cleaned up carefully
    # op.execute('DROP TYPE taskcategoryenum')
    # ### end Alembic commands ###
